### ISSUE TITLE
The Summaries of modules are not designed properly 

### ISSUE THREAD

**Issue by alshubati99** [microsoft/studentambassadors#102]
## Describe the bug
I noticed that the summery files in at the end of the modules are not designed properly.

## To Reproduce
1. Go to 'module summery'
2. Click on 'file edit'
3. Scroll down to 'end of file'
4. add a link to next module md file. 

## Expected behavior
A summary of a lesson should briefly and concisely summarize the main points and key takeaways of the lesson. Here are some tips for writing a summary of a lesson:
1- Identify the main points: Start by reviewing the lesson materials and identifying the most important points that the lesson covered. These will be the points that you want to include in your summary.
2- Keep it brief: A summary should be brief and to-the-point. Try to keep your summary to a few paragraphs or a page at most.
3- Use bullet points or lists: If appropriate, you can use bullet points or lists to organize your summary and make it easier to read.
4- Make sure that it accurately reflects the main points of the lesson and is clear and easy to understand.

## Additional context
It will also be good to add a link to the next lesson after each summery as well as congratulate the student for reaching that point.  

***

**Student Ambassador** 

***

**Comment by eric-camplin** [comment]
@alshubati99 good feedback, can close- added to the takeaways from the Ambassadors - thanks
