### ISSUE TITLE
Readme.md files in each learning path should have instructions not empty. 

### ISSUE THREAD

**Issue by alshubati99** [microsoft/studentambassadors#103]
## Describe the bug
It is noticed that readme.md files in each learning path are empty which is not fine for the courses designed we need to break up the content and make it more easily digestible.

## To Reproduce
1. Go to 'learning path'
2. Click on 'readme.md file'
3. go to edit file
4. add some of the expected behavior points I added down.

## Expected behavior
A README file should provide information about a learning path, including its purpose, how to set it up and use it, and any other relevant details. It is often the first thing that people see when they access the project on GitHub. Here are some things that you might consider including in a README file for a lesson:
1- A brief overview of the lesson, including its purpose and objectives.
2- A list of the materials or resources that are required for the lesson (e.g., software, data sets, etc.).
3- Detailed instructions for setting up the necessary resources and getting the lesson up and running.
4- A list of any prerequisites or assumptions that are made about the learner's background or knowledge.
5- An outline or summary of the topics covered in the lesson.
6- Links to any additional resources or references that might be helpful for learners.
7- Contact information for the lesson's creator or maintainer, in case learners have questions or need additional support.
It's also a good idea to use headings and formatting to make the README file easy to read and navigate. You might use bullet points, numbered lists, or headings to break up the content and make it more easily digestible.

## Additional context
A README file is an important resource for anyone who is accessing a lesson on GitHub, as it provides them with the information they need to understand the purpose and content of the lesson, as well as any requirements or dependencies that are necessary to complete it.
Having a clear and well-written README file can also help to attract learners to your lesson and encourage them to engage with it. By providing a detailed overview of the lesson's content and objectives, you can give learners a sense of what they will learn and what they can expect from the lesson. This can be especially useful if your lesson is part of a larger course or educational program, as it can help learners to understand how the lesson fits into the overall curriculum.
In addition to helping learners, a well-written README file can also be helpful for the lesson's creator or maintainer. By providing clear and concise documentation about the lesson, you can make it easier for others to understand and use your work, and you can also make it easier for yourself to refer back to the lesson's goals and objectives when you are updating or revising it in the future.
***

#### 🎓  **Student Ambassador** 

***

**Comment by eric-camplin** [comment]
@alshubati99 apologies for the randomization - this readme is just an artifact of our build system that we failed to delete in this section.

**Comment by alischumacher** [comment]
Closing issue since this was just an artifact - not part of collection that will be published to Learn
