### ISSUE TITLE
No video content in the learning paths. 

### ISSUE THREAD

**Issue by alshubati99** [microsoft/studentambassadors#104]
## Describe the bug
I strongly believe that adding videos to the content of these learning paths will enhance them and make the learning experience more engaging to learners. .

## To Reproduce
1. Go to 'learning paths'
2. Click on 'any of the lessons'
3.  add video content to the md files. 

## Expected behavior
There are several benefits to using video content when explaining lessons or teaching new material:
Visual aids: Videos can include visual aids such as slides, demonstrations, and animations, which can help learners better understand and retain the information being presented.
Engaging: Videos can be more engaging than text-based content, as they offer a combination of visual and audio elements that can hold the learner's attention.
Convenient: Videos can be more convenient for learners, as they can watch them at their own pace and on their own schedule. This can be especially helpful for those with busy schedules or who prefer to learn at their own pace.
Accessibility: Videos can be more accessible for learners with disabilities, as they can be accompanied by closed captions or transcripts.
Personal touch: Videos can add a personal touch to the learning experience, as learners can see and hear the instructor or presenter. This can help establish a connection with the learner and make the material feel more relatable.

## Additional context
Using video content can be a valuable addition to any lesson or educational material, as it can enhance the learning experience and make the material more accessible and engaging for learners...

***

#### 🎓  **Student Ambassador** 

***

**Comment by eric-camplin** [comment]
@alshubati99 if you could pick your top 5 videos what would you prioritize for https://github.com/microsoft/studentambassadors/tree/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp content?

**Comment by eric-camplin** [comment]
@alshubati99 can close, Added to the general course feedback from Ambassadors - Thanks!
