### ISSUE TITLE
Improve Introduction to C#

### ISSUE THREAD

**Issue by curriee11** [microsoft/studentambassadors#105]
## Improvement to Introduction 
Some introduction missing in [Introduction.md](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M01-write-your-first-c-sharp-code/includes/1-introduction.md)

## Expected Behaviour
C# (pronounced "See Sharp") is a modern,general purpose, object-oriented programming language
The C# programming language allows you to build many types of applications, like:
#### **Student Ambassador** 

***

**Comment by eric-camplin** [comment]
@curriee11 Good feedback. We have some new requirements (restrictions?) with introductions so will be updating them all I think,  I will add a backlog item for the content owner.  Thanks
