### ISSUE TITLE
literal suffix 'm' is not needed

### ISSUE THREAD

**Issue by ayushigeorge** [microsoft/studentambassadors#106]
## Describe the bug
A clear and concise description of what the bug is:
In Step 3: Write a decimal literal to the console output window.
## To Reproduce
1. Go to 'https://github.com/microsoft/studentambassadors/tree/main/Bug-Bash' -> C# Beginners Training 
2. Click on '[2_LP_AZ_create-run-simple-c-sharp-console-applications](https://github.com/microsoft/studentambassadors/tree/main/Bug-Bash/C%23%20Beginner%20Training/2_LP_AZ_create-run-simple-c-sharp-console-applications)' 
3. Scroll down to '[M02-store-retrieve-values-using-variables-c-sharp](https://github.com/microsoft/studentambassadors/tree/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M02-store-retrieve-values-using-variables-c-sharp)/[includes](https://github.com/microsoft/studentambassadors/tree/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M02-store-retrieve-values-using-variables-c-sharp/includes)/2b-exercise-print-literal-values.md'
4. See error in step 3: Step 3: Write a decimal literal to the console

## Expected behavior
Console.WriteLine(12.3m);
output: 12.3

but even after removing m its printing the same output
## Screenshots
This is what we have instructed to do: 

> Write Console.WriteLine(12.3m);

![image](https://user-images.githubusercontent.com/76419649/209547897-fcd9b133-4370-4a2f-9cf9-c525543ab83c.png)
The output is 12.3.

But when I ran the program with 

> Console.WriteLine(12.3); this instruction gave me the exact output 12.3.

>>So the command should be: > Console.WriteLine(12.30m)

![image](https://user-images.githubusercontent.com/76419649/209547908-9f3f242a-c72b-49cd-af74-fbb1d193a39b.png)

## Additional context

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.

***
 **student**, **Student Ambassador**

**Comment by eric-camplin** [comment]
@ayushigeorge  **good catch!** - the sample code instruction should be `Console.WriteLine(12.30m);` not `Console.WriteLine(12.3m);`

and it is probably more useful for the student to see 2 samples, the first being
`Console.WriteLine(12.30);`
and second
`Console.WriteLine(12.30m);`

**Comment by eric-camplin** [comment]
yep - sample should be`Console.WriteLine(12.3**0**m);`

**Comment by ayushigeorge** [comment]
> @ayushigeorge  **good catch!** - the sample code instruction should be `Console.WriteLine(12.30m);` not `Console.WriteLine(12.3m);`
> 
> and it is probably more useful for the student to see 2 samples, the first being
> `Console.WriteLine(12.30);`
> and second
> `Console.WriteLine(12.30m);`

Thank you sir

**Comment by eric-camplin** [comment]
@ayushigeorge this may have got moved our cut in our sources - I pinged the author to address it.  This can be closed.
