### ISSUE TITLE
Missing important concepts on the introduction to C# 

### ISSUE THREAD

**Issue by kelcho-spense** [microsoft/studentambassadors#108]
### Education role: [Beta Student Ambassador](https://studentambassadors.microsoft.com/en-US/studentambassadors/profile/b81411c3-fbca-4a78-86c3-e7360f946b7f)
After reviewing this document [Bug-Bash/C# Beginner Training/1_LP_AZ_get-started-with-c-sharp/M01-write-your-first-c-sharp-code/includes/1-introduction.md](https://github.com/microsoft/studentambassadors/blob/6c65893f4f86d17caa4123e1e700d39bca234961/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M03-perform-basic-string-formatting-c-sharp/includes/2b-exercise-format-strings-using-character-escape-sequences.md) I found some missing information which when I was learning C# few months ago, was confusing to me. As a beginner I had so many questions like
1.	As a beginner I need to know what is c#?
 C# is a statically-typed, compiled, object-oriented language used with the .NET frameworks and runtimes. The official Microsoft C# language reference can be found on [docs.microsoft.com](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp?wt.mc_id=studentamb_225706). Like Java in syntax and structure, C# programs are compiled and executed against a .NET runtime running on a computer. The output of compiling C# code can be called a ‘.NET program’.
2.	What is .NET Runtime?
	is a collection of commands native to the computer operating system that instruct the computer how to interpret and run a .NET program
There are several different .NET runtimes available that give C# flexibility to run in many different locations.
➡️.NET Framework — runs on Windows and support desktop user-interface, console, and server development
➡️.NET Core — runs on Windows, Mac, and Linux with support for desktop user interface, console, and server development.
➡️.NET Core — runs on Windows, Mac, and Linux with support for desktop user interface, console, and server development.
➡️Unity — runs on Windows, Mac, Linux, iOS, and Android devices with support for game development using the Unity3D tools.
➡️Mono — runs on Windows, Mac, Linux, and Web Assembly.
3.	What is Dotnet Framework? 
A .NET Framework is a collection of programming instructions and tools that help you write a program of a specific type. Examples of .NET Frameworks include [Windows Forms](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/?view=netdesktop-6.0&wt.mc_id=studentamb_225706), [ASP.NET](https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps?wt.mc_id=studentamb_225706), [Xamarin iOS](https://dotnet.microsoft.com/en-us/apps/xamarin?wt.mc_id=studentamb_225706), and [Blazor](https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor?wt.mc_id=studentamb_225706)
4.	C# Syntax follows this rules ?
•	C# uses a semi-colon to denote the end of a statement. This is a hard and fast rule, and you’ll get used to it quickly. Every statement in C# needs to end with a semi-colon ; This allows us to also have very flexible spacing in how we structure our code.
•	C# is NOT space sensitive - You can place as many spaces, tabs, or blank lines around your code as you would like.
•	C# IS case sensitive - C# is case-sensitive. All variables, objects, and their interactions must be referenced with the proper casing.
•	Everything in C# is an object - As C# is an object oriented language, everything we want to work with is an object. Objects can be declared of various TYPES and then interacted with. The simplest types in C# are called Built-In Types We can define variables, in-memory storage for a type by preceding the name of the variable we would like to create with the type of the variable we are creating.

A beginner can now understand the basics of C# and the Dotnet framework. This is because Dotnet serves as the engine for C# projects. I believe that after this, a learner will be able to begin coding a hello world program. I've written a blog post on [introduction to C# ](https://medium.com/@kevin_comba/getting-started-with-c-part-1-overview-control-flow-3c590f0b52ee)

**Comment by Jash286** [comment]
Yeah , this would be great if included, it gives a better overview

**Comment by kelcho-spense** [comment]
thank sir
