### ISSUE TITLE
Logo is not shown in the [Ambassador-Blogs/Blog-Format.md] module

### ISSUE THREAD

**Issue by Ishitag26** [microsoft/studentambassadors#110]
## Additional context

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.

***

**Comment by Jash286** [comment]
do fill the how to reproduce the behavior for others to understand where the issue arises

**Comment by alischumacher** [comment]
No information included on bug, closing out issue
