### ISSUE TITLE
Heading should be placed for explanation

### ISSUE THREAD

**Issue by AniqJaved** [microsoft/studentambassadors#112]
## Describe the bug
Heading like trim, replace and upper case must be added to enhance the learning experience

## To Reproduce
1. Go to 'https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/hello-world?tutorial-step=4'
2. Scroll down to see all the explanations of different function

## Expected behavior
There must be proper sections for each function, where we are explaining them.

## Screenshots
![image](https://user-images.githubusercontent.com/86469982/209858780-f94fb88f-5325-4f62-b46a-e666bad7e738.png)

![image](https://user-images.githubusercontent.com/86469982/209858848-b0c77572-fb76-46a4-a560-8faf74cbcd50.png)

### Desktop (please complete the following information):
 - OS: Windows
 - Browser Chrome
 - Version 107.0.5304.88 (Official Build) (64-bit)

### Smartphone (please complete the following information):
 - Device: any
 - OS: any
 - Browser any
 - Version any

## Additional context

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.

***

[@Student](https://github.com/Student) @StudentAmbassador

**Comment by eric-camplin** [comment]
@AniqJaved this is a good suggestion. It is not content from our project.  I will enter an issue on the topic, but I noted that that format (Tutorial) didn't have headings in any of the topics I reviewed - so might be a restriction. Thanks

**Comment by BillWagner** [comment]
Fixed in dotnet/docs#34534
