### ISSUE TITLE
Knowledge Checks are not student friendly

### ISSUE THREAD

**Issue by RashmiNirasha** [microsoft/studentambassadors#113]
## Describe the bug
the multiple-choice answers to the questions are not organized in the correct manner with easy navigation and all the questions are in the same space so it's hard to focus on one.

## Expected behavior
answers should be displayed as, 
(a)
(b) in this manner or with numbered sequence.

## Additional context

***
#Student Ambassador🎓

**Comment by eric-camplin** [comment]
@RashmiNirasha ugh, sorry about that. Our Markdown is hard to read for the knowledge checks and we should have supplied a warning about it. when transformed the knowledge checks look like this https://learn.microsoft.com/en-us/training/modules/csharp-basic-operations/7-knowledge-check

**Comment by alischumacher** [comment]
Closing issue since this will be resolved when markdown is transformed to Learn content
