### ISSUE TITLE
Idea to enrich the introductory part

### ISSUE THREAD

**Issue by Charlie-techLab** [microsoft/studentambassadors#114]
## Describe alternatives you've considered
I think it would be good to put application links made with C# in the introductory part, not by the fact that the current explanation is difficult but so that students get excited to see examples of applications made of what they are about to learn. Those links could contain multimedia tools such as short videos or photos of what can be done with C #.
#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
**I am Student Ambassador**

***

**Comment by eric-camplin** [comment]
@Charlie-techLab Nice, I like it!

**Comment by Charlie-techLab** [comment]
Thanks!

**Comment by eric-camplin** [comment]
@Charlie-techLab This is added to the considerations backlog for or next rev. and **can be closed**. Thanks again, thinking about a video(s) too.

**Comment by Charlie-techLab** [comment]
It has been a great honor for me to be able to collaborate!
