### ISSUE TITLE
Idea to expand a sentence put in the introduction

### ISSUE THREAD

**Issue by Charlie-techLab** [microsoft/studentambassadors#115]
## Describe alternatives you've considered
In the introductory part that says: "By far, the best way to learn how to code is to write as much code as possible", I think it would be good to also add the fact of reading code since it is demonstrated that reading code also helps to be better in programming.

In fact, a study was recently conducted in Spain in which the following results were obtained: those students who had better writing skills were those who had a larger vocabulary. In the case of programming, the broader vocabulary would involve reading the variety of code produced by other programmers (in proportions of complexity that are according to the topics that are gradually introduced) and writing would mean practicing solving exercises and developing projects.

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
**Student Ambassador**
***

**Comment by eric-camplin** [comment]
@Charlie-techLab 👍+1 Yes, reading, writing and reviewing code are all important "best ways".  If you are able to do a pass on some of the content modules and suggest areas and activities, we would be interested in that detailed feedback.  Thanks! 

FYI - we intend the exercises in modules and the guided project modules to provide practice reading and understanding the logic of others code. Whereas the challenge modules are an opportunity for learners to write code without step by step guidance.

**Comment by Charlie-techLab** [comment]
👌 Thank you very much for your feedback and the opportunity to contribute ❤✨!

**Comment by Charlie-techLab** [comment]
@alischumacher @eric-camplin Likewise to you, thank you very much for the opportunity!
