### ISSUE TITLE
Idea for sharing code samples in learning paths 

### ISSUE THREAD

**Issue by Charlie-techLab** [microsoft/studentambassadors#116]
Complementing the idea presented in the previous issue, it is interesting that Bill Gates said that something that has helped him to solve problems has been asking himself 2 simple but very useful questions. The questions are: 1) Who have faced this same problem before us? 2) What can we learn from them?

I think that by giving code examples the students would be applying in a practical way the usefulness of those two previous questions. These sample codes could be submitted by the students themselves. It would also be nice if these provided code samples had documentation explaining their logic and operation. In fact, an award system could be made for students who share code according to predefined quality metrics such as clarity and good explanations.
#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
**I am Student Ambassador**

***

**Comment by Charlie-techLab** [comment]
Ok, again thank you very much for the opportunity. Have a wonderful day 😃!

**Comment by eric-camplin** [comment]
@Charlie-techLab we have added a vnext backlog item to point to optional code practice and completed code.

Thanks

**Comment by Charlie-techLab** [comment]
@alischumacher @eric-camplin Thank you very much for this opportunity to collaborate 💯 
Yes, the idea is basically that in the modules that involve learning a new programming language there are always practice exercises at the end in which the knowledge acquired throughout the entire module is integrated in order to strengthen knowledge and new learning
