### ISSUE TITLE
More information is needed in introductory part

### ISSUE THREAD

**Issue by Hamna7577** [microsoft/studentambassadors#117]
There should be more detail in the introduction part, as a beginner, I want to know what is c#, what is Dotnet, and why I should learn Dotnet with C#?

#### 🎓**Student Ambassador** 

***

**Comment by eric-camplin** [comment]
@Hamna7577 Please list any topic suggestions you have - thank you

**Comment by eric-camplin** [comment]
@Hamna7577 we have added to our VNext backlog to add more explanations - esp. short vides that break up long sections of text.

Thanks
