### ISSUE TITLE
Need pictures for better understanding 

### ISSUE THREAD

**Issue by Hamna7577** [microsoft/studentambassadors#118]
Visualization Improves the Speed of Understanding, and images play a vital role in memory retention so, in my opinion, it would be helpful if there were more pictures to better understand the concept.
#### 🎓**Student Ambassador**

***

**Comment by eric-camplin** [comment]
@Hamna7577 good point - any specific items that you would illustrate? As many as you can list will be appreciated, please include module/unit and any thoughts on type of illustration or rough draft.  Thanks!

**Comment by eric-camplin** [comment]
@Hamna7577 we have added to our top takeaways to add images and video.  We hope to add many images and vids in our VNext release.
