### ISSUE TITLE
Easy way to add and remove comments to multiple lines

### ISSUE THREAD

**Issue by Ujjwal-Madaan** [microsoft/studentambassadors#119]
## Describing the behavior
Adding and removing comments to multiple lines at once.

## To Reproduce
1. Select the lines on which you want to add or remove the comments.
2. Press `Ctrl` + `/` on the keyboard.

## Expected behavior
The desired lines will be commented on or off at once.

## Screenshots
1. This is the text we need to comment
![1](https://user-images.githubusercontent.com/68078768/210156015-606d4a9a-ea18-41e0-9b41-203bca303b8b.png)

2. Select the text
![2](https://user-images.githubusercontent.com/68078768/210156018-9dca00e5-296a-471e-99f5-764203b9fa5f.png)

3. Press `Ctrl` + `/` on the keyboard
![3](https://user-images.githubusercontent.com/68078768/210156026-1b9b8458-8acf-4206-8615-2bbec48afc8f.png)

### Desktop:
 - OS: Windows
 - Browser [Chrome, Edge]
 - Version [108.0.5359.125, 108.0.1462.54]

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.

***

@Student @StudentAmbassador

**Comment by eric-camplin** [comment]
@Ujjwal-Madaan excellent suggestion - added to VNext backlog

Thanks
