### ISSUE TITLE
Variable concepts not deeply discussed

### ISSUE THREAD

**Issue by Taiwrash** [microsoft/studentambassadors#120]
## Describe the bug

This is called an introductory of C# Beginner Content, but the basics of programming are not discussed. Does that mean we only produce for those that are transitioning into the C# language not considering those that are just starting of?

For instance
1. The concept of variable was not deeply and well defined
2. But data types were deeply talk about
3. Different kinds of literal we have were not also explained, only string was explained
 
![image](https://user-images.githubusercontent.com/49725691/210156898-988dccfb-50bc-48de-98cf-7ffa2a963c8a.png)

**Comment by eric-camplin** [comment]
@Taiwrash good feedback - added to our VNext backlog.
Thanks
