### ISSUE TITLE
Enhancement required in [Part 01, Module 01, Unit 03]

### ISSUE THREAD

**Issue by samipak458** [microsoft/studentambassadors#121]
## Describe the bug
**Enhancement required:** Get-started-with-c-sharp/M01-write-your-first-c-sharp-code/includes/3-learn-how-code-works.md

In the unit **learn how code works** before the programming language heading, there should be a heading called **What is programming?** which helps the beginner or student to understand the programming. As someone is learning for the first time, there should be a heading that defines programming which will give more clarification.

## To Reproduce
We can simply reproduce like this 
![image](https://user-images.githubusercontent.com/52650290/211588702-9b26194e-2f5c-4b13-9449-358c9dce55ed.png)

Reference Link: [What is programming?](https://learn.microsoft.com/en-us/training/modules/web-development-101-introduction-programming/2-what-is-programming)

## Expected behavior
It will help beginners and students in better understanding of programming.

## Screenshots
![image](https://user-images.githubusercontent.com/52650290/211588824-d9ee505f-8aed-48c0-89c9-817ccea7624b.png)

### Desktop (please complete the following information):
 - OS: any
 - Browser any
 - Version any

### Smartphone (please complete the following information):
 - Device: any
 - OS: any
 - Browser any
 - Version any

## Additional context
N/A

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
@StudentAmbassador @Student
***

**Comment by alischumacher** [comment]
@samipak458 can you confirm which module this section should be added to?

**Comment by samipak458** [comment]
@alischumacher ma'am this section should be added in **Get started with c sharp/Module 01: write your first c sharp code.

**Comment by alischumacher** [comment]
Thank you for sharing this feedback. Closing this issue as this module is now live on Learn with a section on defining what a programming language is. https://learn.microsoft.com/training/modules/csharp-write-first/3-how-it-works
