### ISSUE TITLE
Microsoft Outlook Extension Error

### ISSUE THREAD

**Issue by varma59** [microsoft/studentambassadors#122]
## Describe the bug
While i installed both Microsoft 365(Office) Extension and Outlook Extension, few times the Microsoft  teams Website is not working and it shows 
**"To open the web app, [change your browser settings] (https://go.microsoft.com/fwlink/?linkid=2136970) to allow third-party cookies or [allow certain trusted domains] (https://go.microsoft.com/fwlink/?linkid=2136970)."**

## To Reproduce
1. 'Install Outlook Extension'
2. 'Sign in with your personal Mail id in Outlook Extension and Your Professional Mail in Microsoft 365 Extension'
3. 'Reload Teams website multiple times '

## Expected behavior
The website wont open and will show "**To open the web app, [change your browser settings](https://go.microsoft.com/fwlink/?linkid=2136970) to allow third-party cookies or [allow certain trusted domains](https://go.microsoft.com/fwlink/?linkid=2136970).**"
And after it i removed the outlook extension and it is working Properly.

## Screenshots
**Without Extension**

![Screenshot 2023-02-03 091123](https://user-images.githubusercontent.com/75376880/216522876-6989cdf1-952a-4913-b1ea-691f76f64265.png)

**With Extension**
![Screenshot 2023-02-03 111157](https://user-images.githubusercontent.com/75376880/216522886-76f7ae2a-1eab-4362-866d-c2f8e8a7c84e.png)

### Desktop (please complete the following information):
 - OS: [Windows 11 Pro]
 - Browser [Chrome]
 - Version [109.0.5414.120 ]

## Additional context
It happens when you open teams website after hours of installing Outlook Extension. When it happened for the first time i removed the outlook Extension and their as been no issue, After few hours again i tried it and by installing the outlook Extension and the same issued popped up.
***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.

**student**, **Student Ambassador** 

***

**Comment by varma59** [comment]
@alischumacher Can you tag this Bug

**Comment by jaberjaber23** [comment]
To resolve the issue, you can try enabling third-party cookies or allowing certain trusted domains in your browser settings as suggested in the error message. You can also try disabling one of the extensions to see if that resolves the issue, (extensions such as: AdBlock extension).

**Comment by varma59** [comment]
I know the solution you mentioned @jaberjaber23 
The issue only comes after logging in two different outlook mails in two different extensions (Microsoft 365 and outlook) and everyone who needs them can't disable them so they enable third party cookies but i reported it so that it will help the Microsoft team to solve the issue rather then user installing third party cookies.

**Comment by alischumacher** [comment]
Thanks for sharing this bug you're facing. If you are still facing this issue, [please share your feedback here](https://support.microsoft.com/en-us/office/how-do-i-give-feedback-on-microsoft-365-2b102d44-b43f-4dd2-9ff4-23cf144cfb11) directly with the Outlook team.
