### ISSUE TITLE
AIBashBug

### ISSUE THREAD

**Issue by suhesha** [microsoft/studentambassadors#127]
## Describe the bug
To talk about cognitive AI no doubt it has raised the standards of understanding user in better way. The way it enhances, adapts and interacts with user to get through its analysis for most is one of it plus points. 
If we talk about the 5 modules introduced during this challenge I faced difficulty in understanding and interpreting if of the statements I would have proffered if there were video presentations which could have demonstrated the execution of steps all in one so that participants could follow it . this way it would have been more easy.
Specially during Build an AI web app by using Python and Flask unit 6 while creating translator services was time consuming , following the video lecture is lot more easier then following the steps one by one after reading it. 
It would be difficult to create the videos presentations for all but it will be easier to use for non-programmers also to follow it after seeing other than debugging the statements

**Comment by BethanyJep** [comment]
This is duplicated from: [duplicate](https://github.com/microsoft/studentambassadors/issues/128l)
