### ISSUE TITLE
AI bugbash

### ISSUE THREAD

**Issue by Aromal-vk** [microsoft/studentambassadors#130]
## Describe the bug
error in sample code give in Exercise - Call Translator service in Build an AI web app by using Python and Flask module.
error:

IndentationError: unexpected unindent

found in the part:

def index_post():
    # Read the values from the form
    original_text = request.form['text']
    target_language = request. Form['language']

## To Reproduce
Follow the instructions and copy the code from the module

![image](https://user-images.githubusercontent.com/123004195/220016091-66e8106d-5573-44dd-94ec-3ba20614667c.png)
![image](https://user-images.githubusercontent.com/123004195/220016152-fa2e316e-b24e-458a-a494-ead4ddacaa90.png)

### Desktop
 - OS: Windows 11

## Additional context

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
**Student Ambassador**
***

**Comment by BethanyJep** [comment]
can you try this instead:
`def index_post():
  # Read the values from the form
  original_text = request.form['text']
  target_language = request. Form['language']`

**Comment by Aromal-vk** [comment]
I was able to fix the error by adding an extra indentation
![image](https://user-images.githubusercontent.com/123004195/224028585-f8e2b535-46d7-47cb-aa96-b389df161e62.png)

**Comment by BethanyJep** [comment]
Great!
