### ISSUE TITLE
Cognitive Services API frontend bug

### ISSUE THREAD

**Issue by prernamittal** [microsoft/studentambassadors#136]
## Describe the bug
Every time the drop-down menu in "Name" is clicked, the display text changes. The same text is displayed for both 1st and 2nd options in the drop-down menu.

## To Reproduce
1. Go to https://westeurope.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/CreateTranscription/console
2. Click on drop-down menu of "Name"
4. See the text displayed in box
5. Select the 1st and 2nd options (same text is displayed)

## Expected behavior
The selected option from the drop-down menu should be displayed correctly

## Screenshots
![image](https://user-images.githubusercontent.com/93262556/221005064-18f2ea4f-795d-4126-baf4-269ce581ebb6.png)
![image](https://user-images.githubusercontent.com/93262556/221005146-20f5dafe-fd2c-4eb6-8094-5d8161bee64c.png)

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 110.0.1587.50 

#### 🎓 Add a tag to this issue for your current education role: **Student Ambassador** 

***

**Comment by BethanyJep** [comment]
![image](https://user-images.githubusercontent.com/44121227/224024575-fb6cca14-c35d-4705-8078-ff02e055819e.png)
![image](https://user-images.githubusercontent.com/44121227/224024689-5a59aa44-4cf4-4cd0-b137-9ddffd244b6f.png)
 on the demo [resource name] is a placeholder, below you are supposed to give your resource name to have it updated. Is this clear?
