### ISSUE TITLE
Cognitive Services Feedback - AI Bug Bash

### ISSUE THREAD

**Issue by aaryan2134** [microsoft/studentambassadors#140]
## Feedback
I followed through and completed all modules in the challenge. What I feel is these are a good starting point and a good, easy and quick way to build a project using Cognitive Services. The instructions are clear and easy to follow.
But one major issue is that these are more like follow along tutorials rather than learning paths. So, there should be some challenges involved
Basically, we can tell what needs to be done with the code and solution hidden. Also, we can give some hints at each step. This will allow better learning and allow developers to learn the process and not only follow along the tutorial.

Adding this will be very beneficial and make it more challenging and increase the learning that happens.

***

#### 🎓 Add a tag to this issue for your current education role: 
**Student Ambassador**
***

**Comment by BethanyJep** [comment]
Thank you for the feedback.
