### ISSUE TITLE
Voice assistant to read out theoretical part of modules.

### ISSUE THREAD

**Issue by Akayush-17** [microsoft/studentambassadors#147]
One of the problem which I faced while going through the modules was that it doesn't have much videos for clear understanding of topics I had to refer google to solve my doubt. Also their was constant lack of concentration as there was too much to read.

## Describe the solution you'd like
The solution can be reducing textual part or may be including a voice assistant that could read out module content. 

## Describe alternatives you've considered
Another such alternative is that ambassador those who have understood that topic may come up with explanation video or a session to clear rest MLSA doubts

## Additional context

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
**StudentAmbassador**
***

**Comment by Muhammad-Qasim11** [comment]
I think for voice assistant you can use Microsoft Edge browser, where read aloud option is available in the top right corner of every tab and you can change settings for your voice assistant as well.
Another point is that you said that other MLSAs should come up with an explanation video, the answer is that you can check out the "Ambassador events" channel in teams where almost each and every product of Microsoft has tutorials and virtual events , conducted by other MLSAs and you can also check other channels like "League-AI and ML" for learning about AI and ML. And in these channels, Microsoft experts conduct sessions every month on different topics which are very detailed and easy to understand, and you can ask questions as well from Microsoft experts.
You can also check the MLSA website and can learn by attending different events at "Microsoft Reactor Livestreams", "Microsoft developer live streams" and "Microsoft learn student Hub" is also great platform to find the learning materials and these materials are very easy to understand.
Moreover, you can check out the workshop repo of Microsoft where each topic has a video tutorial as well. Also, check out the Azure Youtube channel for video content.
I hope this makes sense!

**Comment by BethanyJep** [comment]
Great feedback on this.
