### ISSUE TITLE
Missing of Hands-on platform and video content

### ISSUE THREAD

**Issue by rajazia442** [microsoft/studentambassadors#155]
## Describe the bug
There is no video content in the learning paths and no hands-on training with practical problems.

## To Reproduce
Steps to reproduce the behavior for hands-on:
1. Go to 'Learning path'
2. Click on 'add Hands on Labs'
3. Scroll down to 'Begin labs with instruction and a platform based on Azure so that students can complete lab tasks and earn points.'

Steps to reproduce the behavior for Video:
1. Go to 'Learning path'
2. Click on 'any module'
3. Add video content for each module

## Expected behavior
The learning paths are not designed to provide the kind of hands-on training that would help users learn how to use the tools effectively. There is no video content in the learning paths, nor any hands-on training with practical problems. Because there is no hands-on training, students cannot get feedback from their instructor or peers on whether they are doing things correctly. This can be extremely useful information when learning new things, especially if it is not obvious from simply looking at an example or reading about something online.

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
Student Ambassador
***

**Comment by BethanyJep** [comment]
Hello, this issue has already been submitted, we will be working on this.
