### ISSUE TITLE
Deploying Language studio model

### ISSUE THREAD

**Issue by Muhammad-Qasim11** [microsoft/studentambassadors#160]
## Describe the bug
I created a model in Azure Language studio but when I decided to deploy it and implement it on my website then I was stuck because there were no learning materials available on how to deploy and implement my Langauge studio model.

## Expected behavior
There should be learning materials and a step-by-step process for each and every section of Azure cognitive services deployment and usage because some nontechnical people also use these services, so easy-to-understand learning materials should be available.  

***

#### 🎓 **Student Ambassador** 

***

**Comment by BethanyJep** [comment]
To implement your project, check out the resources in the [ Language Studio homepage:](https://language.cognitive.azure.com/)
![image](https://user-images.githubusercontent.com/44121227/225253858-099eb860-bd0e-4b5f-a94a-4bc4fe4191ac.png)

**Comment by BethanyJep** [comment]
As I have provided links to the resources, I now close this issue.
