### ISSUE TITLE
### Module 3 Custom Vision Exercise Remarks.

### ISSUE THREAD

**Issue by pnet2log** [microsoft/studentambassadors#161]
## Building a Custom Vision Model for Birds endangered species.
Really love the idea of having two methods (No code interface or a few codes using python) of uploading dataset and training/testing the model in the module. Made my learning experience insightful and by extension will aid in mentoring my community members.

# Successfully build, trained and published my model in the exercise of Module 3 (Classify Endangered Species)
![Screenshot (83)](https://user-images.githubusercontent.com/82520832/224491575-63bf8af6-0fd5-44f9-8dc0-c19fc40361e3.png)

Also, observed the unbalanced dataset detected in the red-tailed hawk (Dark morph) training performance indicator as stated in the module.

### Desktop information:
 - OS: [Windows]
 - Browser [Edge]
 - Version [21H2]

***

#### 🎓 **student**, **Student Ambassador**.

***

**Comment by BethanyJep** [comment]
Thank you for the feedback 😄 , glad you enjoyed building the project

**Comment by BethanyJep** [comment]
The dataset has enough data to not overfit or underfit, in this regard we will not be fixing this issue now
