### ISSUE TITLE
Issue in installing node dependencies in the react-app

### ISSUE THREAD

**Issue by akshay-99h** [microsoft/studentambassadors#18]
## Describe the bug
I was trying to install the node modules using ```npm install``` command while following this exercise: [Link to exercise](https://learn.microsoft.com/en-in/training/modules/publish-app-service-static-web-app-api/2-exercise-get-started?pivots=react)
but got a whole lot of cryptic errors instead. I am attaching the log file for further reference.
Log: [2022-09-29T17_09_31_946Z-debug-0.log](https://github.com/microsoft/studentambassadors/files/9677403/2022-09-29T17_09_31_946Z-debug-0.log)

## To Reproduce
1. Clone the repository to your computer.
```bash
git clone https://github.com/<YOUR_GITHUB_USERNAME>/my-static-web-app
```
2. Type the following in your terminal:
```bash
cd my-static-web-app
cd react-app
npm install
```

## Expected behavior
All the npm packages and dependencies should be installed and I should be able to run the ```npm start``` command.

### Running code:
> <img width="1680" alt="Screenshot 2022-09-29 at 11 00 37 PM" src="https://user-images.githubusercontent.com/43650931/193102169-4b56a95c-2f99-429a-9127-9976ba95ba7c.png">
### Error:
> 
<img width="1680" alt="Screenshot 2022-09-29 at 11 01 54 PM" src="https://user-images.githubusercontent.com/43650931/193102343-74556f92-b53e-4764-82d2-27be7b7850b7.png">

### Desktop (please complete the following information):
 - OS: macOS (12.6)
 - Browser N/A
 - Version N/A
 - npm version: 8.11.0

## Additional context
- A possible fix would be bumping up the dependencies with possible severe vulnerabilities

@Student @StudentAmbassador

**Comment by akshay-99h** [comment]
Update: Something similar is happening with the other modules in the Azure Static Web Apps learning path as well.

[Link](https://learn.microsoft.com/en-in/training/paths/azure-static-web-apps/) for the learning path.

**Comment by softchris** [comment]
> Update: Something similar is happening with the other modules in the Azure Static Web Apps learning path as well.
> 
> [Link](https://learn.microsoft.com/en-in/training/paths/azure-static-web-apps/) for the learning path.

@akshay-99h thanks for reporting, please report separate issues for each learn module where you encounter this.

**Comment by softchris** [comment]
> Update: Something similar is happening with the other modules in the Azure Static Web Apps learning path as well.
> 
> [Link](https://learn.microsoft.com/en-in/training/paths/azure-static-web-apps/) for the learning path.

Thank you for reporting this, much appreciated @akshay-99h

**Comment by softchris** [comment]
reported in internal DevOps, 78747

**Comment by saragibby** [comment]
Thank you @akshay-99h for spotting and reporting this issue! The cause of these errors during the install was due to outdated packages in the same applications. We have since had package updates to all the sample applications, and of recent checked last week that all apps were running locally and building. 

Will close this issue as we now have this resolved. As you hit any issues, please open a new issue and we will get it addressed. Thanks again for your time and reporting this to us!
