### ISSUE TITLE
MSLA Under Review Duration

### ISSUE THREAD

**Issue by MarilynHb** [microsoft/studentambassadors#253]
### What product(s) do you have a question about?

MSLA Application

### What is your question?

Hello!!

I have applied to the MSLA program in July, currently my application is under review. Two weeks has passed and I was wondering how much does the review duration usually is?
I'm just too excited to start my journey if I got accepted!

I would love to hear from your experience as a MSLA too!

Thank you!

### What is your current role?

Student

### What technical topic is this question related to?

Other

**Comment by AnthonyByansi** [comment]
Hi @MarilynHb!

Thank you for your enthusiasm about the MLSA program! It's great to see your excitement. The review duration for MLSA applications can vary depending on the volume of applications and the specific timeline of the admissions process. Typically, it takes some time to carefully review all applications to ensure a fair and thorough evaluation.

**Comment by AnthonyByansi** [comment]
> Hi @MarilynHb!
> 
> Thank you for your enthusiasm about the MLSA program! It's great to see your excitement. The review duration for MLSA applications can vary depending on the volume of applications and the specific timeline of the admissions process. Typically, it takes some time to carefully review all applications to ensure a fair and thorough evaluation.

Every applicant's experience may vary, so it's difficult to provide an exact timeline. However, rest assured that the admissions team is working diligently to process applications and will notify you as soon as a decision is reached.

**Comment by hrithikksingh3** [comment]
I have also applied for MLSA in may and its almost end of july but my application is still under review , I don't know why this is happening. As they have review cycle in july and then after july it will be reviewed in october.
