### ISSUE TITLE
Issue: submiting profile after editing

### ISSUE THREAD

**Issue by rh8991** [microsoft/studentambassadors#26]
## Describe the bug
Bug on: [https://studentambassadors.microsoft.com/en-US/studentambassadors/account/](url)

After editing the account profile on the student ambassadors program page, submitting button does not respond, and changes are not saved.

## To Reproduce
1. Go to 'My account' on Microsoft Learn Student Ambassadors.
2. Click on 'Profile'
3. Click on 'Edit Profile
5. See the error

## Expected behavior
As expected changes can't be made and on 'Preview Profile' changes can't be seen.

## Screenshots
![image](https://user-images.githubusercontent.com/103560124/195574251-d86e8991-8752-4ddc-b987-8d949e3cb829.png)

![image](https://user-images.githubusercontent.com/103560124/195574058-143a9b1e-1f3a-4468-bf8f-9e5190a9e10a.png)

### Desktop:
 - OS: Windows 11 Home 
 - Browser firefox
 - Version 105.0.3 (64-bit)

## Additional context
I was trying to add my GitHub account in order to get access to Codespaces.
***

#### 🎓**student**, **Student Ambassador**.

***

**Comment by alischumacher** [comment]
Closing since this issue has been shared with the Ambassador platform engineering team. Issue is isolated to the Student Ambassador account.
