### ISSUE TITLE
Need To Add A Clarification Note.

### ISSUE THREAD

**Issue by KiranAminPanjwani** [microsoft/studentambassadors#27]
## Describe the bug

Bug on [Tutorial: Build an Azure Static Web Apps website with Blazor](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-blazor)
Bug on: [Create and publish a static web app with Gatsby and Azure Static Web Apps](https://learn.microsoft.com/en-us/training/modules/create-deploy-static-webapp-gatsby-app-service/7-exercise-build-deploy-static-app)

Sometimes the repository or organization is not visible to the user, in which case it is essential to include a note describing the solution.

## To Reproduce

- In the document, [Tutorial: Build an Azure Static Web Apps website with Blazor](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-blazor), needs to include a note after the _**eighth point**_.
- There must be a note after the _**fourth point**_ in _Unit 7_ of the document, [Create and publish a static web app with Gatsby and Azure Static Web Apps](https://learn.microsoft.com/en-us/training/modules/create-deploy-static-webapp-gatsby-app-service/7-exercise-build-deploy-static-app).

Note:
If you don't see any repositories, you may need to authorize Azure Static Web Apps on GitHub. Then browse to your GitHub repository and go to Settings > Applications > Authorized OAuth Apps, select Azure Static Web Apps, and then select Grant. For organization repositories, you must be an owner of the organization to grant the permissions.

## Expected behavior

Some people could experience this issue while following the guide. I hope to resolve this issue by including the note.

## Screenshots

The issue could be encountered after the

-  _**Eighth point**_ in the document, [Tutorial: Build an Azure Static Web Apps website with Blazor](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-blazor), 

![image](https://user-images.githubusercontent.com/90326051/195723850-4202bce1-7ab3-4316-b866-3b86c90a3dbf.png)

- _**Fourth point**_ in _Unit 7_ of the document, [Create and publish a static web app with Gatsby and Azure Static Web Apps](https://learn.microsoft.com/en-us/training/modules/create-deploy-static-webapp-gatsby-app-service/7-exercise-build-deploy-static-app).

![image](https://user-images.githubusercontent.com/90326051/195723879-2804cd93-c2a7-46f4-9c98-e53033c375a0.png)

And I want to solve this issue  by adding this note below these points:

![image](https://user-images.githubusercontent.com/90326051/195723465-2aea6140-f14c-41b9-a5d1-df2b607e6c85.png)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

### Smartphone (please complete the following information):
 - Device: Any
 - OS: Any
 - Browser: Any
 - Version: Any

## Additional context

N/A

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.

***

@Student @StudentAmbassador

**Comment by saragibby** [comment]
Thank you @KiranAminPanjwani for recommending this change! The note has been implemented for both the Docs page and Learn Module.
