### ISSUE TITLE
To add an Timer/remainder option in Office extension in browser

### ISSUE THREAD

**Issue by varma59** [microsoft/studentambassadors#29]
## Is your feature request related to a problem? Please describe.
As it is difficult to watch time and join in teams meeting or when we are in other work and finnally we will miss the meeting.

## Describe the solution you'd like
A samll time displaying button in the browser extension bar which shows how much time is there for the next meeting when we are wroking in an chromium based browser when we are working in browser based environment.

## Describe alternatives you've considered
A floating button like in android which shows the user the time  to join the next meeting

## Additional context
![image](https://user-images.githubusercontent.com/75376880/196568951-5d1311c1-58e9-4ce0-87a3-4a3392d6aca8.png)
as the place where more people watch and helps them to join the meeting fast.
***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
**Student Ambassador**
***

**Comment by alischumacher** [comment]
Thanks for sharing this feature idea! Please submit your feature request here in the Microsoft 365 Tech Community: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
