### ISSUE TITLE
Microsoft Teams Video Call Blur issue in browser

### ISSUE THREAD

**Issue by varma59** [microsoft/studentambassadors#30]
## Describe the bug
When i join in a team's meeting from Browser (Microsoft edge or Google Chrome) the teams meeting is shaking and the quality of video decreases and the faces of people whose webcam is working will be shaking continuously.

## To Reproduce
1. Go to 'teams.microsoft.com'
2. Click on 'join a meeting'
3. Scroll down to '..'
4. See error "Effects the presentation we see"

## Expected behavior
when i try to join the meeting from team's application there is no issue when i try to join with browser then the issue starts and when we change tabs and come back to the ongoing meeting the whole presentation screen becomes stuck (Only that page and not the browser or laptop.) and after two seconds it become normal.

## Screenshots

https://user-images.githubusercontent.com/75376880/197006164-34b17368-ad90-4288-ad67-579f081a8532.mp4

### Desktop (please complete the following information):
 - Device: [Asus Tuf Gaming F15]
 - OS: [Windows 11 22H2]
 - Browser [Chrome and edge]
 - Version [22]

## Additional context
And it increases when there are more people with their video working

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
 **Student Ambassador**, **student**
***

**Comment by alischumacher** [comment]
Thanks for sharing this feedback. [Please submit your feedback here](https://support.microsoft.com/en-us/office/give-feedback-in-teams-c0fb6297-22af-4db5-b19b-69e0a6720927) to share directly with the Microsoft Teams team.
