### ISSUE TITLE
Issue on setting up a Git repo exercise – Clarification needed

### ISSUE THREAD

**Issue by sfoteini** [microsoft/studentambassadors#32]
## Describe the bug
Issue on [Introduction to Git: Exercise - Try out Git](https://learn.microsoft.com/el-gr/training/modules/intro-to-git/2-exercise-configure-git)

In the section “Set up your Git repository”, in step 3 and for Git version 2.28.0 or later: It seems that both `git init --initial-branch=main` and `git init -b main` commands initialize a new repository and set the name of the default branch to `main`. So, the user should use only one of these commands.

## To Reproduce
1. In Cloud Shell, type `git –version` to check the GitHub version. (Git version used when reporting this issue: **2.33.4**)
2. Define user’s name and email using
    ```
    git config --global user.name "<USER_NAME>"
    git config --global user.email "<USER_EMAIL>"
    ```
3. Create a folder named Cats.
    ```
    mkdir Cats
    ```
4. Change to the project directory.
    ```
    cd Cats
    ```
5. If you're running Git version 2.28.0 or later, use the following commands to initialize your new repository and set the name of the default branch to `main`.
    ```
    git init --initial-branch=main
    git init -b main
    ```
6. See the output in cloud shell.

## Expected behavior
It seems that the user can use either `git init --initial-branch=main` or `git init -b main` to initialize their new repo and set the name of the default branch to `main`.

Based on [Git documentation](https://git-scm.com/docs/git-init), these two commands are equivalent.
If you use `git init --initial-branch=main` (or `git init -b main`) and then `git status`, you get the following output in cloud shell.
```
Initialized empty Git repository in /home/<user>/Cats/.git/
```
```
On branch main
No commits yet
nothing to commit (create/copy files and use "git add" to track)
```

*(I am a beginner in Git, but it seems that the repo is initialized correctly.)*

## Screenshots
Output if you use both commands:
![issue1](https://user-images.githubusercontent.com/65664664/198848654-711a95b9-f2cf-442b-8d46-9627879de64f.png)

Output if you use only one of the above commands (expected output):
![issue2](https://user-images.githubusercontent.com/65664664/198848665-8f2f150f-943b-430f-b1c3-25ed7f7e53d3.png)

Based on this issue, the content can be modified as follows.
![issue3](https://user-images.githubusercontent.com/65664664/198848701-f87dace8-7f1c-48cd-b8e8-65c3437e5d91.png)

There is also a mistake in the name of the branch in the next step of the instructions (Step 4). The current branch is named `main` and not `master`. The instructions should be modified as follows.
Issue:
![issue4](https://user-images.githubusercontent.com/65664664/198848719-16cddba7-02ea-4b18-b31f-e1ab7866d5cc.png)

Expected:
![issue5](https://user-images.githubusercontent.com/65664664/198848730-b8f95dab-0400-48e2-8338-a7776c72dc15.png)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

### Smartphone (please complete the following information):
 - Device: Any
 - OS: Any
 - Browser: Any
 - Version: Any

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.

***

**student**, **Student Ambassador**

**Comment by PabloNunes** [comment]
Issues to Intro to Git closed.
