### ISSUE TITLE
Azure-static-web-app

### ISSUE THREAD

**Issue by Minahil006** [microsoft/studentambassadors#37]
Show error is creating a repository 

![image_2022-11-10_032727838](https://user-images.githubusercontent.com/89835627/201079316-9b6330da-65e6-475a-9926-0fdaee2c2ba9.png)

**Comment by saragibby** [comment]
Hi @Minahil006! It would be super helpful to get some more information from you on this issue. What were the steps you took to create this GitHUb Action (workflow)? And what error did it give you? 

Thanks! 
Sara

**Comment by alischumacher** [comment]
Closing this issue since no additional details were provided.
