### ISSUE TITLE
Add some exercises and small project in the end of each module

### ISSUE THREAD

**Issue by AftabAhmedAbro** [microsoft/studentambassadors#41]
## Is your feature request related to a problem? Please describe.
It will be the best learning experience if we will have some exercises or small projects at the end of each module. So that whatever we learn in that module we will practice it more and learn effectively.

## Describe the solution you'd like
Adding some small types of tasks to do and submitting screenshots or code snippets for evaluation 

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.

***

**Comment by alischumacher** [comment]
@AftabAhmedAbro can you please provide additional details so that the team can triage this piece of feedback? Specifically, what module(s)/topic(s) are you referring to?

**Comment by alischumacher** [comment]
Closing this issue since no additional details were provided on the specific module / Learning Path.
