### ISSUE TITLE
Windows OS is freezing while opening Microsoft Edge

### ISSUE THREAD

**Issue by varma59** [microsoft/studentambassadors#61]
## Describe the bug
When i tries to add a New page in the vertical window the screen froze, and entire screen is shaking

## To Reproduce
1. Go to 'Microsoft Edge'
2. Click on 'Add new vertical page '
3. Scroll down to 'Add a new page'
4. until you close the window with alt+f4 it continues

## Expected behavior
when doing other operations like watching YouTube, the same thing happened to me. 

## Screenshots

https://user-images.githubusercontent.com/75376880/205477084-52888eba-976a-4a8a-813c-6598e39db58a.mp4
![WhatsApp Image 2022-12-04 at 11 28 34 AM](https://user-images.githubusercontent.com/75376880/205477086-7ac6c31f-34c0-43bd-8081-eddea8038a23.jpeg)

### Desktop (please complete the following information):
 - OS: Windows 11
 - Browser Edge
 - Version 22

## Additional context
until i close the browser it doesn't stop
Tried again and it didn't occur and sometimes when i just open Microsoft edge it happens
***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
Student Ambassador, Windows
***

**Comment by alischumacher** [comment]
Thanks for sharing this feedback. [Please submit your feedback in Feedback Hub](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) to share directly with the Windows team.
