### ISSUE TITLE
Few typos and readability bugs in Work with variable data in C# console applications Module 6.2

### ISSUE THREAD

**Issue by aaryan2134** [microsoft/studentambassadors#63]
## Describe the bug
1. An extra "the" has been added on this line - [Link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/4_LP_AZ_work-variable-data-c-sharp-console-applications/M06-guided-project/includes/2-prepare.md#:~:text=each%20dog%2C%20combine-,the%20the,-physical%20and%20personality)

2. There is no space in "if-elseif-else" - [Link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/4_LP_AZ_work-variable-data-c-sharp-console-applications/M06-guided-project/includes/2-prepare.md#:~:text=loop%20around%20an-,if%2Delseif%2Delse,-construct%20to%20populate)

3. The variable name can be italicized for better understanding and easier reading. For Eg here - [Link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/4_LP_AZ_work-variable-data-c-sharp-console-applications/M06-guided-project/includes/2-prepare.md#:~:text=the%20code%20declares%20the%20ourAnimals%20array)

4. " ``` " has been leftover in the code given
![image](https://user-images.githubusercontent.com/22559451/208109775-57804d1b-d5ae-48b9-98f0-ca72a519c3b1.png)

5. The sentence should be "**in** the starter code" - [Link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/4_LP_AZ_work-variable-data-c-sharp-console-applications/M06-guided-project/includes/2-prepare.md#:~:text=only%20selection%20%221.%20List%20all%20of%20our%20current%20pet%20information%22%20functions%20the%20starter%20code.)

## To Reproduce
1. Go to the respective links
2. Links has already highlighted the position of the area concerned
3. See error

## Expected behavior
1. Extra the should be removed for correcting the typo
2. Space should be added between "if-elseif-else" converting it to "if-else if-else"
3. The variable names in text should be italicized/highlighted. Like _variable_name_
4.  The extra  " ``` " should be removed at the end of the code
5. The sentence should have "**in** the starter code" in the given sentence - "only selection "1. List all of our current pet information" functions the starter code."

### Desktop (please complete the following information):
 - OS: [Windows]
 - Browser [chrome]
 - Version [108]

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
**Student Ambassador**
***

**Comment by eric-camplin** [comment]
- **Fixed✅**Extra the should be removed for correcting the typo
- **Fixed✅ + backlog for global fix📅**Space should be added between "if-elseif-else" converting it to "if-else if-else"
- **Fixed✅**The variable names in text should be italicized/highlighted. Like variable_name
- **By design - for code blocks🆗**The extra " ``` " should be removed at the end of the code
- **Fixed✅**The sentence should have "in the starter code" in the given sentence - "only selection "1. List all of our current pet information" functions the starter code."
@aaryan2134 -great issue, very actionable
