### ISSUE TITLE
Steps in the editor are not the same in the content documentation

### ISSUE THREAD

**Issue by AroojArif12143** [microsoft/studentambassadors#64]
#bug
Step 4 in the training content documentation explains the following code snippets:
1. Console.WriteLine("Hello World!");

2. // Console.WriteLine("Hello World!");

Console.Write("Congratulations!");
Console.Write(" ");
Console.Write("You wrote your first lines of code!");

However Step 4 in the.NET editor describes only mentions the following code: Console.WriteLine("Hello World!");

## To Reproduce
1. Go to 'Step 4 at this link: https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M01-write-your-first-c-sharp-code/includes/2b-exercise-write-your-first-code.md' and see Step 4 in the .NET compiler window here: https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/hello-world?tutorial-step=4

## Expected behavior
The reader will be editing the script in .NET compiler and there will be comments and explanation about each code there corresponding with the content documentation so that the reader is not confused about the steps, sequence and progress of his tasks.

## Screenshots
![step 4 in content](https://user-images.githubusercontent.com/40885002/208940091-c9a1ad12-a7e2-488a-b8af-89923fbd7ce1.png)
]

![step 4 in editor](https://user-images.githubusercontent.com/40885002/208940113-71e29193-5dcc-4f54-874c-7df9458816ad.png)
hrome, safari]

### Desktop (please complete the following information):
 - OS: Windows 10

 - Browser: Chrome

 - Version Google Chrome 105.0

#### Current Role
**engineer**
**student ambassador**
**student**

**Comment by eric-camplin** [comment]
Fixed ✅https://learn.microsoft.com/en-us/training/modules/csharp-write-first/2-exercise-hello-world
