### ISSUE TITLE
Gramatical Errors in Module 1.7

### ISSUE THREAD

**Issue by Sabyasachi-Seal** [microsoft/studentambassadors#66]
## Describe the bug
Currently the summary is the following: 
<h6>
Our goal is to write code that will display simple messages to an output console, and in doing so, become familiar with the syntax. We wrote our first lines of code using basic C# syntax. We learned two techniques for displaying literal-string data to the console. We learned what to look for when we come across an error in our code. And lastly, we identified C# syntax elements like classes and methods, and the purpose of several special symbols that are known as operators.

Congratulations on taking your first steps to building more sophisticated applications.
</h6>

## To Reproduce
1. Go to https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M01-write-your-first-c-sharp-code/includes/7-summary.md

## Expected behavior
Even though this is just the summary, it would be nice to paraphrase it in a more friendly way, explaining how far the user has come after completing this module. For example, this is the para done in a better way:
<h6>
Our goal is to write code that prints a simple message to the output console while familiarizing yourself with the syntax. You wrote the first few lines of code using basic C# syntax. You've learned two techniques for displaying literal string data in the console. You learned what to look for when you get an error in your code. Finally, we identified the purpose of C# syntactic elements such as classes and methods, as well as some special symbols known as operators. You've taken your first steps towards building a more sophisticated application.
</h6>

## Screenshots
![image](https://user-images.githubusercontent.com/36451386/209043479-8430922d-60c8-4a4c-8d70-33d9a18523a3.png)

### Desktop (please complete the following information):
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Version: 143

### Smartphone (please complete the following information):
 - Device: Realme X2 Pro
 - OS: Android 11
 - Browser: Chrome 
 - Version:

## Additional context

***

#### 🎓 Add a tag to this issue for your current education role: **Student Ambassador**

***

**Comment by eric-camplin** [comment]
@Sabyasachi-Seal Thanks  **Added backlog to review all summaries**
