### ISSUE TITLE
Easier way to Open Folders

### ISSUE THREAD

**Issue by Sabyasachi-Seal** [microsoft/studentambassadors#68]
## Is your feature request related to a problem? Please describe.
In articles like [this](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/4_LP_AZ_work-variable-data-c-sharp-console-applications/M05-modify-string-content-using-built-in-string-methods-c-sharp/includes/2-exercise-strings-indexof.md), the way to open a folder in VSCode is to open VS Code and then open the folder through VSCode

## Describe the solution you'd like
I would like to add the method of opening the folder by File Explorer and then typing <code>code .</code> (in the terminal) to open the current folder in VSCode. This will make the whole process a lot easier and for some people (like me) who have trouble finding the folder through VSCode, this will be a nice alternative option.

## Describe alternatives you've considered
I would like to add the method of opening the folder by File Explorer and then typing <code>code .</code> to open the current folder in VSCode. This will make the whole process a lot easier and for some people (like me) who have trouble finding the folder through VSCode, this will be a nice alternative option.

## Additional context

![image](https://user-images.githubusercontent.com/36451386/209052925-ed2f22ee-7240-44b3-bf6b-93669310bc45.png)

***

#### 🎓 Add a tag to this issue for your current education role: **Student Ambassador** 

***

**Comment by Sabyasachi-Seal** [comment]
Thank you, can I work on it ?

**Comment by eric-camplin** [comment]
@Sabyasachi-Seal we are still determining how we will provide starter code to students. That is, we don't know how the students have downloaded files and saved to the development environment location.  You could outline some general suggestion steps and/or feedback that would come after the download - our default is that the learner is working on a local Windows laptop. But, the more generally applicable the steps are to other environments (mac/linux-container) the better. In Windows, with VSCode installed - it can be simple to

-  select file or folder, shift+F10, select "Open with Code." 
or 
- on folder, Shift + Right Click, select "Open with Code"

The same process could be completed with the last step selecting "Open in PowerShell here" and then using `$>code .`

**Comment by Sabyasachi-Seal** [comment]
Okay, so for Windows the two options you mentioned are good, and for other platforms, the 'code .' method will work ad a 3rd option. 

Wouldnt it be better to generalize the entire thing so that its can be used across platforms?

**Comment by eric-camplin** [comment]
Good point, definitely generalize as much as possible across platforms. The issue with `code .` is the opening of the command-line terminal to the file path will have different methods as well.  What is the simplest method in your environment (I assume Linux) for doing the following --> download a .zip and extract to preferred location; open desired folder in vscode; Build and run.

**Comment by Sabyasachi-Seal** [comment]
Got it. Then thats the best way I suppose

**Comment by eric-camplin** [comment]
@Sabyasachi-Seal Added to backlog to get a standard instruction across all modules. issue can be closed.  Thanks for this!

**Comment by Sabyasachi-Seal** [comment]
@eric-camplin great ! Thanks for the response
