### ISSUE TITLE
Knowledge check not clickable in Module 1.6

### ISSUE THREAD

**Issue by Simondelali** [microsoft/studentambassadors#70]
## Describe the bug
The knowledge check in Module 1 can't be clicked to answer the quiz. It shows all correct and Incorrect options.

## To Reproduce
1. Go to Module 01 https://github.com/microsoft/studentambassadors/tree/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M01-write-your-first-c-sharp-code/includes
2. Click on 6-Knowledge-check.md 
3. See error

## Expected behavior
An Interactive interface where we can select our options and it later shows the results

## Screenshots
![Screenshot (177)](https://user-images.githubusercontent.com/83236698/209058969-bf604183-6ec4-4834-ac7f-602a99344e4e.png)

### Desktop (please complete the following information):
 - OS: Windows
 - Browser Opera
 - Version 63

**Comment by eric-camplin** [comment]
@Simondelali sorry about that. Our Markdown is hard to read for the knowledge checks and we should have supplied a warning about it. when transformed the knowledge checks look like this https://learn.microsoft.com/en-us/training/modules/csharp-basic-operations/7-knowledge-check - this is same issue as https://github.com/microsoft/studentambassadors/issues/113

**Comment by alischumacher** [comment]
Closing issue since this will be resolved when transformed into Learn content

**Comment by Simondelali** [comment]
Noted, thanks
