### ISSUE TITLE
Add a module how to run c#  in GitHub codespaces

### ISSUE THREAD

**Issue by varma59** [microsoft/studentambassadors#71]
## Is your feature request related to a problem? Please describe.
As most of the new learners may not know how to install advanced software so we will give a module with the name (Ex: C# in Vs code on Code spaces) and there is no official documentation on how to run C# on GitHub Codespaces.

## Describe the solution you'd like
Just add a small page on the starting of every module how to fork the following week C# files and run them in code spaces rather than downloading them and installing all the software's/Extensions.

## Describe alternatives you've considered
Other Shareable resources like GitHub Repository (But it need to be downloaded) and needful files need to be installed 

## Additional context
![image](https://user-images.githubusercontent.com/75376880/209059194-e4937db1-4d6c-4e19-aad5-e8828ac395f6.png)

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.

**student**, **Student Ambassador**

***

**Comment by eric-camplin** [comment]
@varma59 excellent feedback - **Placing in our backlog**. we are trying to determine what we at Microsoft can supply learners for free (beyond a trial) - hopefully we can supply some version of codespaces or similar.
