### ISSUE TITLE
Few typos and readability bugs in Work with variable data in C# console applications Module 6.1

### ISSUE THREAD

**Issue by aaryan2134** [microsoft/studentambassadors#75]
## Describe the bug
1. An "is" is missing in the line - [Link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/4_LP_AZ_work-variable-data-c-sharp-console-applications/M06-guided-project/includes/1-introduction.md#:~:text=doesn%27t%20use%20data.-,It%20likely,-that%20every%20software)

2. An extra "the" has been added here - [Link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/4_LP_AZ_work-variable-data-c-sharp-console-applications/M06-guided-project/includes/1-introduction.md#:~:text=and%20display%20of-,the%20the,-animals%20available%20for)

3. An extra "to" has been added here - [Link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/4_LP_AZ_work-variable-data-c-sharp-console-applications/M06-guided-project/includes/1-introduction.md#:~:text=you%20to%20investigate-,adding%20to%20features,-to%20the%20app)

4. A "to" is missing here: [Link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/4_LP_AZ_work-variable-data-c-sharp-console-applications/M06-guided-project/includes/1-introduction.md#:~:text=search%20the%20pet-,data%20identify,-animals%20with%20possible)

5. An extra "a" has been added here: [Link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/4_LP_AZ_work-variable-data-c-sharp-console-applications/M06-guided-project/includes/1-introduction.md#:~:text=fundraising%20feature%20to-,include%20a%20suggested,-donation%20data%20and)

6. Double "search" has been added here: [Link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/4_LP_AZ_work-variable-data-c-sharp-console-applications/M06-guided-project/includes/1-introduction.md#:~:text=available%20or%20to-,search%20search,-either%20dogs%20or)

## To Reproduce
1. Go to the respective links
2. Links has already highlighted the position of the area concerned
3. See error

## Expected behavior
1. The line should be "It is likely"
2. Extra "the" should be removed from there
3. The line should be "adding features"
4. The line should be "pet data to identify"
5. The line should be "include suggested donation"
6. Extra "search" should be removed from there

### Desktop (please complete the following information):
- OS: [Windows]
- Browser [chrome]
- Version [108]

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
**Student Ambassador** 
***

**Comment by eric-camplin** [comment]
@aaryan2134 thanks, rewrote the intro and **fixed all.**
