### ISSUE TITLE
Instruction missing to switch to the correct folder in Module 1.6 of Create and run simple C# applications

### ISSUE THREAD

**Issue by aaryan2134** [microsoft/studentambassadors#77]
## Describe the bug
The instruction to move to the correct folder after creating a project using  `dotnet new console -o ./CsharpProjects/TestProject` is missing.
So, when we use `dotnet run` or `dotnet build` as suggested in the module it causes an error

## To Reproduce
1. Go to [Link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/2_LP_AZ_create-run-simple-c-sharp-console-applications/M01-install-configure-visual-studio-code/includes/6-exercise-create-build-run-app.md)
2. Run project as specified on the main folder itself on VS Code

## Expected behavior
We need to change to the created project folder using this command - `cd CsharpProjects/TestProject/`

## Screenshots
![image](https://user-images.githubusercontent.com/22559451/209136771-d88a32da-25f8-490c-aa3e-d93290e1bf7f.png)

### Desktop (please complete the following information):
- OS: [Windows]
- Browser [chrome]
- Version [108]

## Additional context
This is something that may be missed by the students trying the module as well and they would struggle to solve the issue.

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
**Student Ambassador**
***

**Comment by eric-camplin** [comment]
@aaryan2134 **fixed** in restructured lesson published at https://learn.microsoft.com/en-us/training/modules/install-configure-visual-studio-code/7-exercise-create-build-run-app
