### ISSUE TITLE
Project setup files missing in the starter folder for Module 6 of Work with variable data in C# console applications

### ISSUE THREAD

**Issue by aaryan2134** [microsoft/studentambassadors#78]
## To Reproduce
1. Go to [Link](https://github.com/microsoft/studentambassadors/tree/main/Bug-Bash/C%23%20Beginner%20Training/4_LP_AZ_work-variable-data-c-sharp-console-applications/M06-guided-project/LabFiles/Starter)
2. Download and setup according to [Link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/4_LP_AZ_work-variable-data-c-sharp-console-applications/M06-guided-project/includes/2-prepare.md)
3. Run the project as noted here [Link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/4_LP_AZ_work-variable-data-c-sharp-console-applications/M06-guided-project/includes/3-exercise-review-starter-code.md) using `dotnet run`

## Expected behavior
The project setup files are missing which are essential to run and C# project
All of these files should be provided so that the project can run as specified in the instructions.
![image](https://user-images.githubusercontent.com/22559451/209138058-cd284ead-a06b-4424-9355-176ab897e326.png)
These files have been provided in "Create and Run Simple C# applications" - [Link](https://github.com/microsoft/studentambassadors/tree/main/Bug-Bash/C%23%20Beginner%20Training/2_LP_AZ_create-run-simple-c-sharp-console-applications/M07-challenge-project-arrays-iteration-selection/LabFiles/Starter)

## Screenshots
![image](https://user-images.githubusercontent.com/22559451/209137413-bc8b9529-3888-4870-96dd-1dec674917c4.png)
Error caused -
![image](https://user-images.githubusercontent.com/22559451/209137858-a64e9bbc-5398-4d18-af33-68ff0a0e4d0e.png)

### Desktop (please complete the following information):
- OS: [Windows]
- Browser [chrome]
- Version [108]

## Additional context
This can confuse developers as they may not be aware of how to handle this issue and they may get stuck at this point

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
*Student Ambassador**
***

**Comment by eric-camplin** [comment]
@aaryan2134 **fixed** https://learn.microsoft.com/en-us/training/modules/guided-project-work-variable-data-c-sharp/2-prepare
