### ISSUE TITLE
M1 2b "Output window" inconsistent spelling

### ISSUE THREAD

**Issue by GuyAdou** [microsoft/studentambassadors#80]
## Describe the bug

The phrases "Output window", "output pane" and the words "Output", and "output" are spelled differently across the documentation. Those phrases and words listed previously refer to the same thing but spelled with a capital letter in some places and without a capital letter elsewhere. This could be confusing for learners.

## Steps to reproduce the behavior:
1. Go to 2b-exercise-write-your-first-code.md
2.  Scroll down to the first paragraph to see the first spelling of "Output window"
3. See the different spellings across the documentation

## Expected behavior
All references to the "Output window", "Output pane" or "output" should all have the same spelling for consistency.

## Screenshots
<img width="423" alt="image" src="https://user-images.githubusercontent.com/69226314/209360049-53a84a3c-5b46-44c0-bf55-fa50a69dd730.png">

<img width="406" alt="image" src="https://user-images.githubusercontent.com/69226314/209360086-f7ccbcc3-0966-436e-8321-4eb758b5f649.png">

<img width="398" alt="image" src="https://user-images.githubusercontent.com/69226314/209360113-2f6d2ef8-ef82-445b-a402-1e977a2db9b5.png">

### Desktop (please complete the following information):
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: Version 108.0.1462.54 (Official Build) (64-bit)

***

🎓 Add a tag to this issue for your current education role: #student, #Student Ambassador

**Comment by eric-camplin** [comment]
@GuyAdou **fixed** - no more "output Pane" all "output" lower case.  Thanks!
