### ISSUE TITLE
M1 2b: Refer back to Step 1 in Step 4

### ISSUE THREAD

**Issue by GuyAdou** [microsoft/studentambassadors#81]
## Describe the bug
Step 4, "Comment out the previous line of code, then add new lines of code in the .NET Editor to print a new message" could be better by exactly pointing out the code users need to modify in the documentation.

## To Reproduce
1. Go to 2b-exercise-write-your-first-code.md.
3. Scroll down to Step 4: Comment out the previous line of code, then add new lines of code in the .NET Editor to print a new message

## Expected behavior
Specify to the user that the line of code to which they need to add the forward slashes are the code they wrote in Step 1, like this: _"Modify the code you wrote [in Step 1] so that it's prefixed by a code comment using two forward slashes // and add new lines of code to match the following code snippet":_

## Screenshots
<img width="432" alt="image" src="https://user-images.githubusercontent.com/69226314/209362767-8173a973-cfd0-445b-8711-d2e18e29bc56.png">

### Desktop (please complete the following information):
- OS: Windows 11
- Browser: Microsoft Edge
- Version: Version 108.0.1462.54 (Official Build) (64-bit)

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.

***

**Comment by eric-camplin** [comment]
@GuyAdou was **fixed** by displaying the intended code with the comment (`// Console.WriteLine("Hello World!");`)
