### ISSUE TITLE
Introduction of "Note" to Enhance Better Understanding

### ISSUE THREAD

**Issue by Devbysteph** [microsoft/studentambassadors#82]
## Describe the bug
The step 2 in [4-exercise-setting-getting-values-from-variables.md](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M02-store-retrieve-values-using-variables-c-sharp/includes/4-exercise-setting-getting-values-from-variables.md), has an additional Point which is important to be noted by the reader, however, the point is embedded in line with the content of "Step 2". 

 The Addition of a note will ensure easy readability and proper grasping of the content.

## To Reproduce
I suggest that the point is highlighted as an important point to note in the step, I describe it further below.

## Expected behavior
The expected behavior is to have an additional note to step 2 to help the reader understand that it is important to note the point. Here is the expected structure for "Step 2"
### Step 2: Declare a variable and assign a value to it

To assign a value to a variable, you use the *assignment operator*, which is a single equals character `=`.

Add the following code in the code editor:

```c#
string firstName;
firstName = "Bob";
```
> [!NOTE]
> Assigning a value is also referred to as "setting the variable", or simply, a "set" operation.
#### This is a screenshot of what is currently available in the lesson step:
![image](https://user-images.githubusercontent.com/67132776/209402344-336220d3-1ac0-4023-a69b-33f4e82d67eb.png)

#### This is the proposed expected behaviour to enhance the readability and ensure that the reader takes note of the important point:
![image](https://user-images.githubusercontent.com/67132776/209402970-39b2be8f-9bd3-4d68-be5f-06fb74d67525.png)

### Desktop (please complete the following information):
 - OS: all
 - Browser: all
 - Version: all

### Smartphone (please complete the following information):
 - Device: all
 - OS: all
 - Browser: all
 - Version: all

## Additional context

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
Student, Student Ambassador

***

**Comment by eric-camplin** [comment]
@Devbysteph good issue, I submitted **fixed** as proposed in a pull request to the author - Thanks!
