### ISSUE TITLE
[C# Bug Bash] Information missing at <write-your-first-c-sharp-code> module from first LP

### ISSUE THREAD

**Issue by OscarSantosMu** [microsoft/studentambassadors#85]
## Describe the bug
Some programming concepts are introduced in [3-learn-how-code-works.md](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M01-write-your-first-c-sharp-code/includes/3-learn-how-code-works.md), and I believe this should be mentioned in [1-introduction.md](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M01-write-your-first-c-sharp-code/includes/1-introduction.md)

## To Reproduce
1. Go to [3-learn-how-code-works.md](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M01-write-your-first-c-sharp-code/includes/3-learn-how-code-works.md)
2. Review the content.
3. Go back to [1-introduction.md](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M01-write-your-first-c-sharp-code/includes/1-introduction.md) and you will notice there is no comments related to this.

## Expected behavior
At [1-introduction.md](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M01-write-your-first-c-sharp-code/includes/1-introduction.md)

In this module, you'll:

* Write your first lines of C# code.
* Learn foundational programming concepts.
* Use two different techniques to print a message to a text console.
* Diagnose errors when you type code incorrectly.
* Identify different C# syntax elements like operators, classes, and methods.

By the end of this module, you'll be able to understand foundational programming concepts and write C# code to print a message to a text console, like the Windows command prompt. These lines of code will give you your first look at the C# syntax, and immediately provide invaluable insights. In fact, this module will introduce many new ideas, which we'll expand upon in other modules.

## Additional context
By having a list of everything that is in the module, the student can decide if studying that module is worthy, given that he/she does not know the contents.

***

#### 🎓 **Student Ambassador**

***

**Comment by eric-camplin** [comment]
@OscarSantosMu valid feedback, not sure it will get fixed but moving to backlog.  Thanks
