### ISSUE TITLE
Inconsistent font size and inconsistencies in formatting between steps in Module 2 of Explore the Visual Studio Code user interface.

### ISSUE THREAD

**Issue by iamhbc** [microsoft/studentambassadors#86]
## Additional context

***

#### 🎓Student Ambassador

***

**Comment by OscarSantos98** [comment]
Please provide more info in the Issue body (e.g. link to the module, screenshots, etc)

**Comment by eric-camplin** [comment]
@iamhbc **Fixed** -This seems to have been addressed on the live site https://learn.microsoft.com/en-us/training/modules/install-configure-visual-studio-code/
