### ISSUE TITLE
Readability bug in the formatting of the table in [1_LP_AZ_get-started-with-c-sharp/M05-guided-project-calculate-print-student-grades/includes/2b-prepare.md]

### ISSUE THREAD

**Issue by anshgoyalevil** [microsoft/studentambassadors#87]
## Describe the bug
In the project overview, the list of student assignment grades is formatted incorrectly. The names of the students should be aligned, and the grades should be aligned in separate columns. Here is an example of how the list could be formatted correctly.

## To Reproduce
1. Go to this [link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M05-guided-project-calculate-print-student-grades/includes/2b-prepare.md)
2. Go to the first table with student names and their grades.

## Expected Table:
```Output
Student     Grades
Sophia      93  87  98  95  100

Andrew      80  83  82  88  85

Emma        84  96  73  85  79

Logan       90  92  98  100 97
```
## Previous Table:
```Output
Sophia: 93, 87, 98, 95, 100

Andrew: 80, 83, 82, 88, 85

Emma:   84, 96, 73, 85, 79

Logan:  90, 92, 98, 100, 97
```

***

**🎓Student Ambassador**

***

**Comment by eric-camplin** [comment]
@anshgoyalevil added to backlog as a suggestion - thanks!
