### ISSUE TITLE
A readability bug in the output table in [studentambassadors/Bug-Bash/C# Beginner Training/1_LP_AZ_get-started-with-c-sharp/M06-guided-project-calculate-final-gpa/includes/2b-prepare.md]

### ISSUE THREAD

**Issue by anshgoyalevil** [microsoft/studentambassadors#88]
## Describe the bug
In the project overview, the list of grades and credit hours is formatted incorrectly. They must be in a column for the better readability. Here is an example of how the list could be formatted correctly.

## To Reproduce
1. Go to this [link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M06-guided-project-calculate-final-gpa/includes/2b-prepare.md)
2. Go to the output table

## Expected behavior

```Output
Student: Sophia Johnson

Course				Grade		Credit Hours
English 101			4		3
Algebra 101			3		3
Biology 101			3		4
Computer Science I		3		4
Psychology 101			4		3

Final GPA:			3.35
```

## Previous Behavior
```Output
Student: Sophia Johnson

Course			Grade	Credit Hours
English 101			4		3
Algebra 101			3		3
Biology 101			3		4
Computer Science I	3		4
Psychology 101		4		3

Final GPA:			3.35
```

***

🎓 **Student Ambassador**

***

**Comment by eric-camplin** [comment]
@anshgoyalevil **Fixed** on live site https://learn.microsoft.com/en-us/training/modules/guided-project-calculate-final-gpa/2-prepare
