### ISSUE TITLE
A readability bug in table in [Part 1, Module 6, Exercise 3]

### ISSUE THREAD

**Issue by anshgoyalevil** [microsoft/studentambassadors#89]
## Describe the bug
In the project overview, the list in ```Point 5``` containing Course and Grade titles, is not formatted correctly.

## To Reproduce
1. Go to this [link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M06-guided-project-calculate-final-gpa/includes/3-exercise-store-data.md)
2. Go to the table in point ```5```

## Expected behavior

```
Course			    Grade		
English 101		     A
Algebra 101		     B
Biology 101		     B
Computer Science I	     B
Psychology 101		     A
```

Previous Behaviour:

    
    Course			    Grade		
    English 101		     A
    Algebra 101		     B
    Biology 101		     B
    Computer Science I	 B
    Psychology 101	     A
    

***

🎓**Student Ambassador**

***

**Comment by eric-camplin** [comment]
@anshgoyalevil thanks **Fixed** on live site now https://learn.microsoft.com/en-us/training/modules/guided-project-calculate-final-gpa/3-exercise-store-data
