### ISSUE TITLE
A readability bug in the output table in [Part 1, Module 06, Exercise 6]

### ISSUE THREAD

**Issue by anshgoyalevil** [microsoft/studentambassadors#90]
## Describe the bug
In the check your work output, the data is formatted in such a way that it would be hard for the student to read the text. The correct formatting must be as follows.

## To Reproduce
1. Go to this [link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M06-guided-project-calculate-final-gpa/includes/6-exercise-format-strings.md#check-your-work)
2. Go to the list

## Expected behavior

```Output
Student: Sophia Johnson

Course				Grade		Credit Hours
English 101			4		3
Algebra 101			3		3
Biology 101			3		4
Computer Science I		3		4
Psychology 101			4		3

Final GPA:			3.35
```

## Previous Behavior
```Output
Student: Sophia Johnson

Course			Grade	Credit Hours
English 101			4		3
Algebra 101			3		3
Biology 101			3		4
Computer Science I	3		4
Psychology 101		4		3

Final GPA:			3.35
```

***

🎓 **Student Ambassador**

***

**Comment by eric-camplin** [comment]
@anshgoyalevil thanks this is now **Fixed** on the live site https://learn.microsoft.com/en-us/training/modules/guided-project-calculate-final-gpa/6-exercise-format-strings
