### ISSUE TITLE
Readability bug due to markdown in [Part 2, Module 01, Exercise 5]

### ISSUE THREAD

**Issue by anshgoyalevil** [microsoft/studentambassadors#92]
## Describe the bug
In the [Part 2, Module 01, Exercise 5], there is a command ```dotnet --version``` used throughout the text, but it is not enclosed in the backticks due to which, it would be hard for the student to copy which exactly is the command, and which is normal text.

## To Reproduce
1. Go to this [link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/2_LP_AZ_create-run-simple-c-sharp-console-applications/M01-install-configure-visual-studio-code/includes/5-exercise-install-dotnet.md)
2. Find the command ```dotnet --version``` in the whole text (occurred 3 times), using the ```Ctrl-F``` command on Windows.

## Expected behavior
It should be formatted with backticks ```dotnet --version``` instead of just **dotnet --version**

***
🎓**Student Ambassador**
***

**Comment by eric-camplin** [comment]
@anshgoyalevil yep that's good feedback and now **fixed** on live site https://learn.microsoft.com/en-us/training/modules/install-configure-visual-studio-code/6-exercise-install-dotnet
