### ISSUE TITLE
Readability bug due to markdown in [Part 2, Module 01, Exercise 6]

### ISSUE THREAD

**Issue by anshgoyalevil** [microsoft/studentambassadors#94]
## Describe the bug
In the [Part 2, Module 01, Exercise 6], there is a command ```dotnet new console -o ./CsharpProjects/TestProject``` used in point 6 of "Create a C# console application in a specified folder", but it is not enclosed in the backticks due to which, it would be hard for the student to copy which exactly is the command, and which is normal text.

## To Reproduce
1. Go to this [link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/2_LP_AZ_create-run-simple-c-sharp-console-applications/M01-install-configure-visual-studio-code/includes/6-exercise-create-build-run-app.md)
2. Find the command ```dotnet new console -o ./CsharpProjects/TestProject``` in point 6 of "Create a C# console application in a specified folder"

## Expected behavior
It should be formatted with backticks ```dotnet new console -o ./CsharpProjects/TestProject``` instead of just **dotnet new console -o ./CsharpProjects/TestProject**

***
🎓**Student Ambassador**
***

**Comment by eric-camplin** [comment]
@anshgoyalevil good catch and **fixed** in source and will go live with next publishing [here](https://learn.microsoft.com/en-us/training/modules/install-configure-visual-studio-code/7-exercise-create-build-run-app)    - ETA 3/17
