### ISSUE TITLE
Link not working in [Part 2, Module 03, Exercise 2]

### ISSUE THREAD

**Issue by anshgoyalevil** [microsoft/studentambassadors#96]
## Describe the bug
Some links are not working in [Part 2, Module 03, Exercise 2], and thus, giving a 404 response code. The links are [Call methods from the .NET Class Library using C#](https://github.com/MicrosoftDocs/learn-pr/blob/53d6c48677ed00dbd14f214c651607aee9063458/learn/modules/csharp-call-methods/?azure-portal=true) and [Evaluate Boolean expressions to make decisions in C#](https://github.com/MicrosoftDocs/learn-pr/blob/53d6c48677ed00dbd14f214c651607aee9063458/learn/modules/csharp-evaluate-boolean-expressions/?azure-portal=true).

## To Reproduce
1. Go to this [link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/2_LP_AZ_create-run-simple-c-sharp-console-applications/M03-add-decision-logic-to-your-code-using-c-sharp/includes/2-exercise-use-if-statement.md)
2. Check all the links in this markdown, or directly open the links provided in the "Describe the Bug" section.

## Expected behavior
The links should work, and must not give a 404 error.

## Screenshots
![404 error](https://i.imgur.com/8mzmODS.png)

***

🎓 **Student Ambassador**
***

**Comment by eric-camplin** [comment]
Expected - This is a Private Repo 'https://github.com/MicrosoftDocs/learn-pr/blob' - link resolves during publishing build

same issue as https://github.com/microsoft/studentambassadors/issues/97

**Comment by alischumacher** [comment]
Closing issue since this will be resolved when published
