### ISSUE TITLE
Link not working in [Part 3, Module 01, Exercise 4]

### ISSUE THREAD

**Issue by anshgoyalevil** [microsoft/studentambassadors#97]
## Describe the bug
A link is not working in [Part 3, Module 01, Exercise 4], and thus, giving a 404 response code. The links are [Calling different kinds of methods in the .NET Class Library](https://github.com/MicrosoftDocs/learn-pr/blob/e4dc71145761d815a6bc23ad00d2c8365f7597d5/learn/modules/csharp-call-methods/3-call-methods?azure-portal=true).

## To Reproduce
1. Go to this [link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/3_LP_AZ_add-logic-c-sharp-console-applications/M01-evaluate-boolean-expressions-make-decisions-c-sharp/includes/4-exercise-challenge-conditional-operator.md)
2. Check all the links in this markdown, or directly open the links provided in the "Describe the Bug" section.

## Expected behavior
The links should work, and must not give a 404 error.

## Screenshots
![404 error](https://i.imgur.com/2TZfL3O.png)

***

🎓 **Student Ambassador**
***

**Comment by alshubati99** [comment]
Yes I noticed this problem as well

**Comment by eric-camplin** [comment]
@anshgoyalevil Sorry - this is an internal link to an internal private repo topic that gets processed through the build system.

any link starting with 'https://github.com/MicrosoftDocs/learn-pr/blob' is OK and will resolve when published

**Comment by alischumacher** [comment]
Closing since this will be resolved when published
