### ISSUE TITLE
The lessons files are not linked to each other. 

### ISSUE THREAD

**Issue by alshubati99** [microsoft/studentambassadors#99]
## Describe the bug
I noticed that the lessons are written in md files which are not linked to each other. For example: each lesson should be linked to the next or previous lesson md file to make it easier to navigate through lessons. 

## To Reproduce
1. Go to 'md file'
2. Click on 'edit md file'
3. Scroll down to 'the end of the file'
4. add a link to the previous or next lesson. 

## Expected behavior
I expected that the files are connected to each other so it is easy to navigate through the course. 

### Desktop (please complete the following information):
 - OS: [windows 11]
 - Browser [chrome]
 - Version [2.1]

## Additional context
I hope this problem can be fixed. I have seen many other bugs in these learning paths, yet, I think this one really needs to be fixed. It is crucial to keep the flow of the lessons. 

***

#### 🎓 **Student Ambassador** 

***

**Comment by eric-camplin** [comment]
@alshubati99 Items are linked once published - example https://learn.microsoft.com/en-us/training/modules/intro-to-azure-fundamentals/what-is-cloud-computing at the bottom of page automatically goes to next topic

**Comment by alischumacher** [comment]
Closing issue since this will be resolved once published
